### ISSUE TITLE
Log more information about network errors

### ISSUE THREAD

**Issue by larf311** [RelationalAI/rai-sdk-javascript#27]
Right now all we see in the logs is:

```
Error: Request failed due to a connectivity issue. Please check your network connection.
   webpack://_N_E/../node_modules/@relationalai/rai-sdk-javascript/dist/web/rai-sdk-javascript.modern.js at line 1
   webpack://_N_E/../node_modules/@relationalai/rai-sdk-javascript/dist/web/rai-sdk-javascript.modern.js at line 1
   webpack://_N_E/../node_modules/@relationalai/rai-sdk-javascript/dist/web/rai-sdk-javascript.modern.js at line 1
   webpack://_N_E/../node_modules/@relationalai/rai-sdk-javascript/dist/web/rai-sdk-javascript.modern.js at line 1
```

If we also reported the http response code & message that would be super helpful.

**Comment by denisgursky** [comment]
I don't think that it's possible. You see this because there were no response. There's probably no way to access that Status column from the network tab either.

**Comment by larf311** [comment]
Closing as there is nothing we can do :(

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-5369](https://relationalai.atlassian.net/browse/RAI-5369).

_This link is only accessible to employees of RelationalAI._
