### ISSUE TITLE
128 unsigned integers are displayed incorrectly

### ISSUE THREAD

**Issue by larf311** [RelationalAI/rai-sdk-javascript#40]
<img width="635" alt="image" src="https://user-images.githubusercontent.com/3720330/183091895-fe1a33d4-5535-4548-8d72-d0b8a72a4af1.png">

**Comment by gkastrinis** [comment]
Should I be able to see the changes? (because I don't with a refresh on the console)

**Comment by denisgursky** [comment]
@gkastrinis Not yet. I'll ping you.

**Comment by gkastrinis** [comment]
Ah, sorry. To eager to try :P

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-6280](https://relationalai.atlassian.net/browse/RAI-6280).

_This link is only accessible to employees of RelationalAI._
