### ISSUE TITLE
handle `illegal tag: field no 0 wire type 0` errors

### ISSUE THREAD

**Issue by vilterp** [RelationalAI/rai-sdk-javascript#46]
Encountered in https://github.com/RelationalAI/rai-ux/issues/1498, when decoding proto metadata of empty transactions.

These should go away once an engine-side bug fix rolls out.

cc @denisgursky

**Comment by denisgursky** [comment]
See https://github.com/RelationalAI/rai-sdk-javascript/pull/47

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-6342](https://relationalai.atlassian.net/browse/RAI-6342).

_This link is only accessible to employees of RelationalAI._
