### ISSUE TITLE
Better detection of fetch

### ISSUE THREAD

**Issue by sswatson** [RelationalAI/rai-sdk-javascript#64]
When we assign `globalThis.fetch || nodeFetch` to the variable `fetch`, we open ourselves up to the risk that the environment has defined `globalThis.fetch` to some sort of fetch polyfill won't work with the SDK.

For example, this happens in a Next.js API route, since they assign to `globalThis.fetch` a version of node-fetch that does not implement `formData`.

See this Slack thread for more details: https://relationalai.slack.com/archives/C02C9AV2LL9/p1667401442961529

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-7740](https://relationalai.atlassian.net/browse/RAI-7740).

_This link is only accessible to employees of RelationalAI._

**Comment by denisgursky** [comment]
Fixed in https://github.com/RelationalAI/rai-sdk-javascript/pull/72
