### ISSUE TITLE
Create test action

### ISSUE THREAD

**Issue by larf311** [RelationalAI/rai-sdk-javascript#68]
We need to create a github action that runs the tests that conforms to the same interface as all the others:

E.g. it should look almost identical to this:
https://github.com/RelationalAI/rai-sdk-csharp/blob/main/.github/actions/test/action.yml

The tests also need to support custom headers.

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-7959](https://relationalai.atlassian.net/browse/RAI-7959).

_This link is only accessible to employees of RelationalAI._
